
outfile:add.o del.o exit.o save.o show.o sort.o student.o
	cc add.c add_file.c del.c del_all.c Exit.c save.c show.c sort.c student.c -o outfile
add.o:add.c
	cc -c add.c
add_file.o:add_file.c
	cc -c add_file.c
del_all.o:del_all.c
	cc -c del_all.c
del.o:del.c
	cc -c del.c
exit.o:exit.c
	cc -c Exit.c
save.o:save.c
	cc -c save.c
show.o:show.c
	cc -c show.c
sort.o:sort.c
	cc -c sort.c
student.o:student.c
	cc -c student.c
	
